# Generated by Django 4.2.5 on 2024-01-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0003_paticipants_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="paticipants",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
